name: Deploy Lambda Function

on:
  push:
    branches:
      - develop
      - test
      - cloudgate-migration

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # GitHub 리포지토리의 코드를 체크아웃
      - uses: actions/checkout@v2

      # Lambda 함수 배포를 위한 코드 압축
      - name: Prepare deployment package
        run: zip -r function.zip .

      # AWS 자격 증명 구성
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # AWS Lambda에 함수 코드 배포
      - name: Deploy to AWS Lambda
        env:
          FUNCTION_NAME: ${{ github.repository }}
        run: |
          # 리포지토리 이름에서 함수 이름 추출
          FUNCTION_NAME=$(echo $FUNCTION_NAME | cut -d'/' -f2)

          # 브랜치가 'test'인 경우 함수 이름에 '_test' 접미사 추가
          if [ "${{ github.ref }}" == "refs/heads/test" ]; then
            FUNCTION_NAME="${FUNCTION_NAME}_test"
          fi

          # 브랜치가 'cloudgate-migration'인 경우 특정 함수 이름 사용
          if [ "${{ github.ref }}" == "refs/heads/cloudgate-migration" ]; then
            FUNCTION_NAME="${FUNCTION_NAME}_cloudgate"
          fi

          # AWS CLI를 사용하여 Lambda 함수 코드 업데이트
          aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://function.zip